### ISSUE TITLE
Mod没有被加载(需安装对应Forge、Fabric版本）

### ISSUE THREAD

**Issue by RoB8080** [Windmill-City/IngameIME-Minecraft#1]
In my understanding, this version should support both forge and fabric.
But in game I can't see any effect and cannot find it in mod list.

PS. I add some chinese letter in jar files' name for better sort and classify

* Mod version: **IngameIME-forge-1.16.4-1.1**
* JRE version: **1.8.0_281**
* Game version: **1.16.5**
* Fabric-loader: **0.11.1**
* Dependencies:
    - **fabric-api-0.29.4+1.16**
    - **fabric-language-kotlin-1.4.21+build.1**
    - **cloth-api-1.4.9**
    - **satin-1.5.1**

**Comment by Windmill-City** [comment]
no, you should go to https://www.curseforge.com/minecraft/mc-mods/ingameime/files and download the fabric version
