### ISSUE TITLE
1.15.2 一输入就崩溃

### ISSUE THREAD

**Issue by Sanluli36li** [Windmill-City/IngameIME-Minecraft#10]
与 #6 完全一致
不过我mod比他少很多

崩溃报告:
[crash-2021-06-17_20.03.17-client.txt](https://github.com/Windmill-City/IngameIME-Minecraft/files/6670015/crash-2021-06-17_20.03.17-client.txt)
Mod包传不上来 发个网盘链接
https://36li.lanzoui.com/iYBNIqac5ib

**Comment by Sanluli36li** [comment]
不出意外的话，应该是optifabric冲突了

**Comment by Windmill-City** [comment]
是Opti的问题
