### ISSUE TITLE
告示牌輸入無法切換語言

### ISSUE THREAD

**Issue by flandretw** [Windmill-City/IngameIME-Minecraft#11]
Forge 版本：1.16.5 36.1.25
IngameIME 版本：1.6.1
kotlinforforge：1.12.2
輸入法：微軟注音
在遊戲中無法在告示牌介面進行切換語言。
如果是我的問題的話請告訴我；如果資訊不足我可以進一步提供。

**Comment by Windmill-City** [comment]
按Home键可以切换吗

**Comment by flandretw** [comment]
按Home鍵有IME出現，但實際上仍然無法切換語言

**Comment by flandretw** [comment]
噢等等，我剛剛嘗試了幾次終於按出來了。

**Comment by Windmill-City** [comment]
语言是按shift切的，这个与输入法有关

**Comment by flandretw** [comment]
但是只有在告示牌的介面才需要這麼做，聊天欄並不需要使用 Home 鍵。

**Comment by Windmill-City** [comment]
这个应该是有些优化mod比如optifine修改了告示牌方面的代码，导致自动开启功能失效了
优化mod太多，兼容它们困难重重，所以还是手动操作吧

**Comment by flandretw** [comment]
僅使用 IngameIME、cloth-config、kotlinforforge 依然有這個問題，雖然可以透過 Home 進行切換，但實在是不方便。

**Comment by Windmill-City** [comment]
很尴尬，我这里怎么试都是正常的，你是用curseforge client装的吗？

**Comment by flandretw** [comment]
curseforge client 指的是 forge 客戶端嗎？

**Comment by Windmill-City** [comment]
![image](https://user-images.githubusercontent.com/14292823/123578239-f8794580-d807-11eb-8fe0-342ac848a5ad.png)

**Comment by flandretw** [comment]
我並不是使用 curseforge 客戶端，我使用原版登入器+forge 客戶端。

**Comment by Windmill-City** [comment]
我的意思是你用这个客户端来装mod，它会自动下载对应的依赖，启动器还是原版启动器

**Comment by Windmill-City** [comment]
你下载1.6.2版本的，这个版本你按一次热键开启输入法后，鼠标不发生移动输入法不会关闭，这样可能比较好用一点

**Comment by flandretw** [comment]
剛剛試了一下，目前是可以正常使用的。^^
