### ISSUE TITLE
MaLilib快捷键无法使用

### ISSUE THREAD

**Issue by Facvoid** [Windmill-City/IngameIME-Minecraft#16]
可能是MaLilib没有把快捷键放在设置里，导致Mod不知道MaLilib的快捷键，从而过滤掉这些快捷键

**Comment by Windmill-City** [comment]
不是很理解你说的问题，我的Mod没有过滤快捷键的功能

**Comment by Facvoid** [comment]
可是**依赖MaLilib**的模组在**手动切换输入法**后无法使用

**Comment by Windmill-City** [comment]
在输入法开启状态下，游戏是无法响应按键的，要关掉输入法才行

**Comment by Windmill-City** [comment]
我测试了依赖MaLiLib的Item Scoller，发现是可以正常工作的
你具体是哪个mod不能工作，期望表现是什么？实际表现又是什么？

**Comment by Facvoid** [comment]
我是在使用**Tweakeroo，Litematica**时，在**聊天栏打不出字时**切换输入法，然后就无法使用**Tweakeroo，Litematica**的快捷键了。(输入法只有微软拼音和英语输入法，游戏默认用英语输入法)

**Comment by Windmill-City** [comment]
应该是因为你开了输入法之后没有把它关上

**Comment by Windmill-City** [comment]
我这里测的是正常的，你要按一下切换输入法的键把它关上才行

**Comment by Windmill-City** [comment]
不过正常来说不是能自动开关吗？怪了

**Comment by Windmill-City** [comment]
刚刚发现，用Win+空格切换输入法之后输入法就把键盘的焦点抢了，但是切换回去就没问题了

**Comment by Facvoid** [comment]
我测试了两次，第一次，进入世界后，我在Tweakeroo里设置一个快捷键，游戏里可以生效，切换输入法后，无法使用快捷键，切换回中文后还可以使用快捷键，再次切换时视角无法移动，快捷键不生效。第二次把文件删干净了，只有mods文件夹，测试时不切换快捷键可以使用，切换后快捷键无法使用，视角可以移动，切回后快捷键无法使用，视角可以转动

**Comment by Facvoid** [comment]
[latest.log](https://github.com/Windmill-City/IngameIME-Minecraft/files/7512395/latest.log)

**Comment by Facvoid** [comment]
模组:
	tweakeroo-fabric-1.17.1-0.10.0-dev.20210710.155746
	modmenu-2.0.14
	minihud-fabric-1.17.1-0.19.0-dev.20210707.150016
	malilib-fabric-1.17.1-0.10.0-dev.26
	litematica-fabric-1.17.1-0.0.0-dev.20210906.183617
	IngameIME-fabric-1.17-pre5-1.6.4
	fabric-language-kotlin-1.6.5+kotlin.1.5.31
	fabric-api-0.42.1+1.17
	cloth-config-5.1.40-fabric
	cloth-api-2.0.54
版本：
	1.17.1 Fabric 0.11.7

**Comment by Facvoid** [comment]
[日志中有Error的日志.txt](https://github.com/Windmill-City/IngameIME-Minecraft/files/7512471/Error.txt)
[日志中有WARN的日志.txt](https://github.com/Windmill-City/IngameIME-Minecraft/files/7512472/WARN.txt)

**Comment by Windmill-City** [comment]
你在关闭聊天栏之后，不要去用系统快捷键切换输入法

**Comment by Facvoid** [comment]
是不是说把切换输入法的按键关掉就行了

**Comment by Windmill-City** [comment]
不是关按键，是不要用系统快捷键切输入法

**Comment by Facvoid** [comment]
可是，有时候我在游戏里是中文输入法，然后在游戏里玩了大概5分钟时，打开聊天栏，输入法就时英文了

**Comment by CV-Chen** [comment]
游戏Log里读取的Mod：
        - amecsapi@1.1.4+mc21w16a
	- antighost@1.17.1-fabric0.36.1-1.1.4
	- architectury@2.6.35
	- autoconfig1u@3.2.2
	- betterf3@1.1.5
	- capes@1.2.1
	- carpet@1.4.47
	- cleancut@1.17-4.0-fabric
	- clientcommands@2.5.5
	- clientcommands-scripting@1.2
	- cloth-api@2.0.54
	- cloth-basic-math@0.6.0
	- cloth-client-events-v0@2.0.54
	- cloth-common-events-v1@2.0.54
	- cloth-config2@5.1.40
	- cloth-datagen-api-v1@2.0.54
	- cloth-scissors-api-v1@2.0.54
	- cloth-utils-v1@2.0.54
	- crowdin-translate@1.3+1.17
	- cursormod@1.3.0
	- easiervillagertrading@1.17.1-fabric0.36.1-1.5.4
	- entityculling@1.3.3
	- fabric@0.42.1+1.17
	- fabric-api-base@0.4.0+5847535018
	- fabric-api-lookup-api-v1@1.3.1+5847535018
	- fabric-biome-api-v1@3.2.2+5847535018
	- fabric-blockrenderlayer-v1@1.1.6+5847535018
	- fabric-command-api-v1@1.1.4+5847535018
	- fabric-commands-v0@0.2.3+5847535018
	- fabric-containers-v0@0.1.13+5847535018
	- fabric-content-registries-v0@0.3.1+5847535018
	- fabric-crash-report-info-v1@0.1.6+5847535018
	- fabric-dimensions-v1@2.0.13+5847535018
	- fabric-entity-events-v1@1.3.1+5847535018
	- fabric-events-interaction-v0@0.4.11+5847535018
	- fabric-events-lifecycle-v0@0.2.2+5847535018
	- fabric-game-rule-api-v1@1.0.8+5847535018
	- fabric-item-api-v1@1.2.5+5847535018
	- fabric-item-groups-v0@0.3.1+5847535018
	- fabric-key-binding-api-v1@1.0.5+5847535018
	- fabric-keybindings-v0@0.2.3+5847535018
	- fabric-language-kotlin@1.6.5+kotlin.1.5.31
	- fabric-lifecycle-events-v1@1.4.5+5847535018
	- fabric-loot-tables-v1@1.0.5+5847535018
	- fabric-mining-level-api-v1@1.0.2+6d0fac4218
	- fabric-mining-levels-v0@0.1.5+6d0fac4218
	- fabric-models-v0@0.3.1+5847535018
	- fabric-networking-api-v1@1.0.14+5847535018
	- fabric-networking-blockentity-v0@0.2.12+5847535018
	- fabric-networking-v0@0.3.3+5847535018
	- fabric-object-builder-api-v1@1.10.11+6d0fac4218
	- fabric-object-builders-v0@0.7.5+6d0fac4218
	- fabric-particles-v1@0.2.5+5847535018
	- fabric-registry-sync-v0@0.7.13+5847535018
	- fabric-renderer-api-v1@0.4.5+5847535018
	- fabric-renderer-indigo@0.4.9+5847535018
	- fabric-renderer-registries-v1@3.2.6+6d0fac4218
	- fabric-rendering-data-attachment-v1@0.1.6+5847535018
	- fabric-rendering-fluids-v1@0.2.1+6d0fac4218
	- fabric-rendering-v0@1.1.7+6d0fac4218
	- fabric-rendering-v1@1.10.1+6d0fac4218
	- fabric-resource-loader-v0@0.4.9+5847535018
	- fabric-screen-api-v1@1.0.5+5847535018
	- fabric-screen-handler-api-v1@1.1.9+5847535018
	- fabric-structure-api-v1@1.1.14+5847535018
	- fabric-tag-extensions-v0@1.2.2+5847535018
	- fabric-textures-v0@1.0.7+5847535018
	- fabric-tool-attribute-api-v1@1.3.1+eb76084f18
	- fabric-transfer-api-v1@1.5.1+6d0fac4218
	- fabricloader@0.11.7
	- fancymenu@2.3.6
	- ferritecore@3.0.1
	- fiber@0.23.0-2
	- gbfabrictools@1.3.4+1.17
	- hydrogen@0.3
	- ingameime@1.6.4
	- inventoryhud@3.4.0
	- inventoryprofilesnext@1.0.3
	- iris@1.1.3-starline+build.596
	- itemmodelfix@1.0.2+1.17
	- java@17
	- konkrete@1.3.0
	- lambdynlights@2.0.2+1.17
	- lazydfu@0.1.2
	- libzoomer@0.2.1+1.17
	- litematica@0.0.0-dev.20210906.183617
	- lithium@0.7.3
	- loadmyresources@1.0.1
	- malilib@0.10.0-dev.26
	- minecraft@1.17.1
	- minihud@0.19.0-dev.20210707.150016
	- modmenu@2.0.5
	- mousewheelie@1.7.3+mc1.17.1-pre1
	- multiconnect-api@1.4
	- nofade@1.17-2.0.0
	- notenoughcrashes@3.4.4+1.17
	- okzoomer@5.0.0-beta.2+1.17
	- org_aperlambda_lambdajcommon@1.8.1
	- org_jetbrains_kotlin_kotlin-reflect@1.5.31
	- org_jetbrains_kotlin_kotlin-stdlib@1.5.31
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.5.31
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.5.31
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm@1.5.2
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.5.2
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm@1.3.0
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm@1.3.0
	- reeses-sodium-options@1.2.0
	- roughlyenoughitems@6.1.329
	- smoothboot@1.16.5-1.6.0
	- sodium@0.3.2+IRIS2-build.159
	- sodium-extra@0.3.5
	- spruceui@3.2.0+1.17
	- tweakeroo@0.10.0-dev.20210710.155746
	- tweed@3.0.0-beta.26
	- windowedfullscreen@1.0.0
	- worldedit@7.2.6+4b2d1e7
	- xaerobetterpvp@21.21.0
	- xaeroworldmap@1.18.1

**Comment by Windmill-City** [comment]
你在聊天栏开启的时候是可以切换输入法的，但是在聊天栏关闭之后就不要去切换了

**Comment by Windmill-City** [comment]
你没看过代码可能不大理解，在你打开聊天栏之后，游戏内部会将输入法开启状态置为True，这时候你是可以切换输入法的，关闭聊天栏后，游戏将输入法开启状态置为False，你切换输入法的信息游戏就收不到了，这时输入法在操作系统那边是开启的，自然输入的焦点就不在游戏上，而是在输入法上面

**Comment by Facvoid** [comment]
处理器	Intel(R) Core(TM) i9-10850K CPU @ 3.60GHz   3.60 GHz
机带 RAM	16.0 GB (15.9 GB 可用)
系统类型	64 位操作系统, 基于 x64 的处理器
笔和触控	没有可用于此显示器的笔或触控输入
版本	Windows 11 企业版
版本	21H2
安装日期	‎2021-‎8-‎28-‎周六
操作系统版本	22000.346
体验	Windows 功能体验包 1000.22000.346.0

**Comment by Facvoid** [comment]
我看mcmod百科上面的演示是Windows10，我电脑是Windows11

**Comment by Facvoid** [comment]
源代码演示图片也是Windows10

**Comment by SGK2401** [comment]
> 刚刚发现，用Win+空格切换输入法之后输入法就把键盘的焦点抢了，但是切换回去就没问题了

谢谢。总结就是切屏一次就能正常使用了。

**Comment by IJustWantANamePlease** [comment]
这是malilib的老毛病了，弹个开始菜单就好了，和ingameIME没啥关系
