### ISSUE TITLE
[1.16.5]启动时游戏崩溃(安装VC++运行库)

### ISSUE THREAD

**Issue by EnterFor** [Windmill-City/IngameIME-Minecraft#2]
崩溃报告：https://paste.ubuntu.com/p/Q7vj9nsQhp/
已经有两名玩家出现了同样的崩溃（我自己没出现过）

**Comment by Windmill-City** [comment]
是在什么情况下崩溃的，打开gui，还是在加载过程中

**Comment by Windmill-City** [comment]
如果有debug.log(在logs文件夹下)，hs_err_xxx.log(在.minecraft文件夹下)也顺带附上

**Comment by Windmill-City** [comment]
[IngameIME-forge-1.16.4-1.3-debug.zip](https://github.com/Windmill-City/IngameIME-Minecraft/files/5944555/IngameIME-forge-1.16.4-1.3-debug.zip)
把这玩意的后缀改成jar，放到mods里面，然后运行一次游戏，把 .minecraft/logs/debug.log 发给我就好了

**Comment by EnterFor** [comment]
> [Ingameime - 锻造 - 1.16.4 - 1.3 -](https://github.com/Windmill-City/IngameIME-Minecraft/files/5944555/IngameIME-forge-1.16.4-1.3-debug.zip)
> 调试.zip [贾尔，]，[mods]，]，[.minecraft/日志/调试.log]

运行这个模组，需不需要删除IngameIME及前置？

**Comment by EnterFor** [comment]
> [IngameIME-forge-1.16.4-1.3-debug.zip](https://github.com/Windmill-City/IngameIME-Minecraft/files/5944555/IngameIME-forge-1.16.4-1.3-debug.zip)
> 把这玩意的后缀改成jar，放到mods里面，然后运行一次游戏，把 .minecraft/logs/debug.log 发给我就好了

运行这个模组，需不需要删除IngameIME及前置？

**Comment by Windmill-City** [comment]
替换旧的IngameIME

**Comment by EnterFor** [comment]
您有一份文件待查收！即刻点击链接获取文件：https://cowtransfer.com/s/0bd079a741b64b 或进入 cowtransfer.com 获取，在首页输入取件码：105918（24小时内有效）

文件过大，里面有很多高清修复的错误日志，不知道对您有没有帮助。好不容易才弄到一个log，与玩家沟通较困难。

**Comment by Windmill-City** [comment]
https://www.microsoft.com/zh-CN/download/details.aspx?id=52685

**Comment by Windmill-City** [comment]
应该是缺少了vc++2015运行库引起的，点上面链接下载并安装（正常人的电脑还能缺这个的吗

**Comment by EnterFor** [comment]
我真是佛了，玩家的电脑是真拉啊

**Comment by Windmill-City** [comment]
https://support.microsoft.com/zh-cn/topic/%E6%9C%80%E6%96%B0%E6%94%AF%E6%8C%81%E7%9A%84-visual-c-%E4%B8%8B%E8%BD%BD-2647da03-1eea-4433-9aff-95f26a218cc0

**Comment by Windmill-City** [comment]
如果还不行就下这个链接里的
![image](https://user-images.githubusercontent.com/14292823/107794040-ec797380-6d91-11eb-8100-a06376cfac6e.png)

**Comment by EnterFor** [comment]
估计玩家们这样教都不懂，已经建议他们不行就删除的方案
