### ISSUE TITLE
1.19支援?

### ISSUE THREAD

**Issue by tentenlee100** [Windmill-City/IngameIME-Minecraft#26]
大概甚麼時候會完成1.19的支援呢?

**Comment by zty012** [comment]
1.19改一下fabric.mod.json，手动创建一下config就好了

**Comment by a0916105** [comment]
@shikukuya 
> 手动创建一下config

是什麼意思？

後記：我已經改用IMBlocker

**Comment by Indekkusu545** [comment]
我已经提交了一个pr #30 来支持1.19 fabric。在发布到curseforge之前，您可以在 [**此处**](https://github.com/Indekkusu545/IngameIME-Minecraft/releases) 下载预构建的jar包。
