### ISSUE TITLE
1.16.5的Forge版本使用此模组后切换中文输入法游戏内无法响应键盘触发

### ISSUE THREAD

**Issue by z1vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv** [Windmill-City/IngameIME-Minecraft#29]
**1.16.5**的**Forge**版本使用此模组后切换中文输入法游戏内无法响应键盘触发
具体表现为当玩家切换中文输入法后无法在游戏内做出任何动作及打开任何GUI，切换回英文输入法后恢复正常。
输入法为：微软输入法 ；系统版本：Windows10 ；模组版本：1.6.3
目前装有的与输入法有关的模组如下：
1. imblocker  链接：https://www.curseforge.com/minecraft/mc-mods/imblocker
2. JustEnoughCharacters  链接：https://www.curseforge.com/minecraft/mc-mods/just-enough-characters

**Comment by Windmill-City** [comment]
本mod与imblocker冲突
