### ISSUE TITLE
Meanwhile, Linux players...

### ISSUE THREAD

**Issue by Neubulae** [Windmill-City/IngameIME-Minecraft#3]
哈哈yes竟然2021年了ibus还没法在游戏内打字
https://www.bilibili.com/read/cv4246084/
不知道能不能参考这个？;-.-

**Comment by Neubulae** [comment]
虽然fcitx可以是可以……

**Comment by Windmill-City** [comment]
暂时不考虑对Linux、Mac OS的兼容，如果你pr过来我很乐意接受
