### ISSUE TITLE
增添模组跨平台支持信息

### ISSUE THREAD

**Issue by msparkles** [Windmill-City/IngameIME-Minecraft#36]
As far as we could tell, there's no public information on if it works on non-Windows platforms, and to what extent.

Could there be a notice for it? Even just a "untested but might work" could serve. It's really hard to tell if it's worth trying because there's no telling whether or not it strictly depends on Windows APIs.

---

看不太出來有沒有「是否能在非 Windows 環境下運作」的公開資訊，也看不出來能運作到什麼程度。

能否有個區塊寫著支援程度？就算只有一個「沒有測試但可能運作」也好。現在很難看出來到底質不值得嘗試使用，因為沒辦法直接判斷是否有用到絕對專屬 Windows 平台才有的 API.

**Comment by Windmill-City** [comment]
此模组暂时只支持Windows平台，使用了专有API
