### ISSUE TITLE
1.19.3---

### ISSUE THREAD

**Issue by zty012** [Windmill-City/IngameIME-Minecraft#37]
之前改过fabric.mod.json，一直提示装satin，装了satin也不行

**Comment by AkarinLiu** [comment]
[minecraft-exported-crash-info-2023-02-15T16-13-22.zip](https://github.com/Windmill-City/IngameIME-Minecraft/files/10740787/minecraft-exported-crash-info-2023-02-15T16-13-22.zip)

**Comment by Windmill-City** [comment]
暂时不会更新
