### ISSUE TITLE
java.lang.NoClassDefFoundError: kotlinx/coroutines/GlobalScope

### ISSUE THREAD

**Issue by Puqns67** [Windmill-City/IngameIME-Minecraft#4]
奇怪的问题，麻烦看一下，forge版在打开任意与输入有关的界面时崩溃，主界面可以进入，点单人游戏就崩溃了，fabric版正常
[[Forge版日志]](https://paste.ubuntu.com/p/wvS3Vq7Qhn/)[[Forge版Crash-Reports]](https://paste.ubuntu.com/p/8GqDcr9pJs/)[[Fabric版日志]](https://paste.ubuntu.com/p/vsbfBwtS8N/)

**Comment by Puqns67** [comment]
标题没打上去

**Comment by Windmill-City** [comment]
是kotlinforforge的问题，要等它那边更新

**Comment by Windmill-City** [comment]
可以先回退到kotlinforforge-1.10.0版本

**Comment by Puqns67** [comment]
我先试试

**Comment by Puqns67** [comment]
确实没问题了

**Comment by Puqns67** [comment]
等kotlinforforge修吧（issue打的这么快的吗
