### ISSUE TITLE
1.19.1~1.19.4？

### ISSUE THREAD

**Issue by Colorflow-exe** [Windmill-City/IngameIME-Minecraft#40]
如题 请支持1.19.1~1.19.4的版本

**Comment by AkarinLiu** [comment]
是的，我需要这个模组，请作者立即更新。@Windmill-City

**Comment by AkarinLiu** [comment]
> 如题 请支持1.19.1~1.19.4的版本

如果不更新的话，将考虑另起炉灶，因为现在Minecraft已经更新到了1.20版本了。
@Leung288

**Comment by Windmill-City** [comment]
暂时不会更新
