### ISSUE TITLE
可以定制1.12.2版本吗，有偿的

### ISSUE THREAD

**Issue by ZHI-CCC** [Windmill-City/IngameIME-Minecraft#46]
我们非常需要1.12.2版本的mod
我愿意定制1.12.2版本，提供较多的薪资

**Comment by Windmill-City** [comment]
开发这个Mod还挺耗精力的, 起码得干一个月; 这个Mod本身也是开源软件, Java前端和C++后端都有提供源码, 如果你真的需要可以自行移植.
