### ISSUE TITLE
[1.16.5]在任意区域使用输入法输入内容游戏会立即崩溃

### ISSUE THREAD

**Issue by GaN8373** [Windmill-City/IngameIME-Minecraft#5]
[debug.log](https://github.com/Windmill-City/IngameIME-Minecraft/files/6336952/debug.log)
[latest.log](https://github.com/Windmill-City/IngameIME-Minecraft/files/6336953/latest.log)
crash-reports内没有生成文件，只能发logs目录里的日志给你了
![image](https://user-images.githubusercontent.com/80253667/115256286-abbb2380-a161-11eb-932f-8ffa5afa67fb.png)

游戏版本：1.16.5
MOD版本：1.4

**Comment by Windmill-City** [comment]
是只有在JEI输入才崩溃，还是任何文本框输入都崩溃

**Comment by Windmill-City** [comment]
你看看你的.minecraft文件夹里面有没有hs_err_pidxxx的文件

**Comment by GaN8373** [comment]
> 你看看你的.minecraft文件夹里面有没有hs_err_pidxxx的文件

有的，关于是不是只有JEI，我只试了JEI。我换别的试试看再回复你
[hs_err_pid29200.log](https://github.com/Windmill-City/IngameIME-Minecraft/files/6340975/hs_err_pid29200.log)

**Comment by GaN8373** [comment]
> 是只有在JEI输入才崩溃，还是任何文本框输入都崩溃

我在主界面尝试输入内容也崩溃了，下文是崩溃日志。时间是14：05
[hs_err_pid12040.log](https://github.com/Windmill-City/IngameIME-Minecraft/files/6341011/hs_err_pid12040.log)
[debug.log](https://github.com/Windmill-City/IngameIME-Minecraft/files/6341013/debug.log)
[latest.log](https://github.com/Windmill-City/IngameIME-Minecraft/files/6341014/latest.log)
