### ISSUE TITLE
1.15.2输入会崩溃

### ISSUE THREAD

**Issue by SunnySlopes** [Windmill-City/IngameIME-Minecraft#6]
[crash-2021-04-26_09.26.27-client.txt](https://github.com/Windmill-City/IngameIME-Minecraft/files/6373704/crash-2021-04-26_09.26.27-client.txt)
1.15.2游戏版本
1.5mod版本

**Comment by Windmill-City** [comment]
能把mods发一下吗

**Comment by Windmill-City** [comment]
这个应该是有奇怪的mod冲突了，但没有mods文件夹没法调

**Comment by SunnySlopes** [comment]
抱歉刚刚看到邮件，这是我的mod文件夹
















在 2021-04-30 10:18:20，"Windmill-City" ***@***.***> 写道：

这个应该是有奇怪的mod冲突了，但没有mods文件夹没法调

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

从网易126邮箱发来的超大附件
mods.zip (48.62M, 2021年6月19日 15:20 到期)
下载
